const loader=document.querySelector(".page-loader");window.addEventListener("load",()=>setTimeout(()=>loader.style.display="none",450));
const nav=document.getElementById("navbar"), menu=document.getElementById("menuBtn"), navMenu=document.getElementById("navMenu");
window.addEventListener("scroll",()=>nav.classList.toggle("scrolled",scrollY>30));
menu.addEventListener("click",()=>navMenu.classList.toggle("open"));
document.querySelectorAll("nav a").forEach(a=>a.addEventListener("click",()=>navMenu.classList.remove("open")));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.12});
document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
const counter=document.querySelector("[data-count]");let counted=false;
const counterObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&!counted){counted=true;let n=0,t=setInterval(()=>{n+=4;if(n>=100){n=100;clearInterval(t)}counter.textContent=n},18)}}));
counterObs.observe(counter);
const glow=document.querySelector(".cursor-glow");window.addEventListener("pointermove",e=>{glow.style.left=e.clientX+"px";glow.style.top=e.clientY+"px"});
const sections=[...document.querySelectorAll("main section[id]")], links=[...document.querySelectorAll("nav a")];
const activeObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){links.forEach(l=>l.classList.toggle("active",l.getAttribute("href")==="#"+e.target.id))}}),{rootMargin:"-35% 0px -55% 0px"});
sections.forEach(s=>activeObs.observe(s));