const students={ICT001:{name:"Demo Student",grade:"Grade 10",rank:4,marks:[["ICT Theory",86,"A"],["Excel Practical",78,"A"],["Revision Test 01",71,"B"]]},ICT002:{name:"Sample Student",grade:"Grade 09",rank:7,marks:[["ICT Theory",76,"A"],["Practical",69,"B"],["Revision Test 01",62,"C"]]},ICT003:{name:"Test Student",grade:"Grade 11",rank:2,marks:[["Database",91,"A"],["Web Practical",88,"A"],["Model Paper 01",79,"A"]]}};let current=null;
const login=()=>{const key=document.getElementById("indexInput").value.trim().toUpperCase(),s=students[key];if(!s)return alert("Index number not found. Try ICT001.");current={...s,index:key};document.getElementById("loginBox").hidden=true;document.getElementById("dashboard").hidden=false;document.getElementById("studentName").textContent=s.name;document.getElementById("studentMeta").textContent=`${key} • ${s.grade} • Rank #${s.rank}`;render("results")};
document.getElementById("loginBtn").onclick=login;document.getElementById("indexInput").addEventListener("keydown",e=>e.key==="Enter"&&login);
document.getElementById("logoutBtn").onclick=()=>{current=null;document.getElementById("dashboard").hidden=true;document.getElementById("loginBox").hidden=false};
document.querySelectorAll(".dash-tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".dash-tabs button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");render(b.dataset.tab)});
function render(tab){const c=document.getElementById("tabContent");if(tab==="results")c.innerHTML=`<div class="tab-grid"><div class="data-card"><small>AVERAGE</small><strong>${Math.round(current.marks.reduce((a,x)=>a+x[1],0)/current.marks.length)}%</strong><p>Current performance</p></div><div class="data-card"><small>RANK</small><strong>#${current.rank}</strong><p>Class ranking</p></div><div class="data-card"><small>STATUS</small><strong class="grade-a">PASS</strong><p>Keep going!</p></div></div><table class="mark-table"><thead><tr><th>ASSESSMENT</th><th>MARK</th><th>GRADE</th></tr></thead><tbody>${current.marks.map(m=>`<tr><td>${m[0]}</td><td>${m[1]}</td><td class="${m[2]==="A"?"grade-a":""}"><b>${m[2]}</b></td></tr>`).join("")}</tbody></table>`;
else if(tab==="notes")c.innerHTML=`<div class="resource-list"><div class="resource"><b>ICT Lesson Notes — ${current.grade}</b><span>PDF ↗</span></div><div class="resource"><b>Quick Revision Sheet</b><span>PDF ↗</span></div><div class="resource"><b>Practical Activity Guide</b><span>OPEN ↗</span></div></div>`;
else if(tab==="papers")c.innerHTML=`<div class="resource-list"><div class="resource"><b>Model Paper 01 — ${current.grade}</b><span>OPEN ↗</span></div><div class="resource"><b>ICT Practical Paper</b><span>OPEN ↗</span></div><div class="resource"><b>Exam Prediction Paper</b><span>OPEN ↗</span></div></div>`;
else c.innerHTML=`<div class="update"><h3>2026 New Class Update</h3><p>Class resources and latest revision materials have been updated.</p></div><div class="update"><h3>Upcoming Revision</h3><p>Check your class group for the latest schedule.</p></div>`}
const q=new URLSearchParams(location.search).get("view");if(q){document.querySelector(`[data-tab="${q}"]`)?.click() }